language: python
python:
- 2.7
- 3.4
notifications:
email: false
 
# Setup anaconda
before_install:
- wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
- chmod +x miniconda.sh
- ./miniconda.sh -b
- export PATH=/home/travis/miniconda2/bin:$PATH
- conda update --yes conda
- conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
- conda install --yes -n condaenv pip
- source activate condaenv
# The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
- sudo rm -rf /dev/shm
- sudo ln -s /run/shm /dev/shm
- pip install codecov
# Install packages
install:
- conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib nose
- pip install mock coverage coveralls
- python setup.py install
 
# Run test
script:
- nosetests --with-coverage --cover-package=lingpy --logging-level=INFO
 
# Calculate coverage
after_success:
- codecov
