"""
Setup-Script for LingPy
"""
from setuptools import setup, find_packages


setup(
    name="lingpy",
    description="Python library for quantitative tasks in historical linguistics",
    long_description=open('README.md').read(),
    long_description_content_type="text/markdown",
    author="Johann-Mattis List and Simon Greenhill and Robert Forkel",
    author_email="info@lingpy.org",
    version="2.6.6",
    packages=find_packages(
        ".",
        exclude=[
            "lingpy._plugins",
            "_plugins",
            "*._plugins",
            "_plugins.*",
            "*._plugins.*",
            "build",
            "private",
            "lingpy.egg-info",
            "dist",
            "lib",
        ],
    ),
    package_dir={"": "."},
    install_requires=[
        "numpy",
        "appdirs",
        "networkx>=2.0,<=2.2",
        "tqdm",
        "six",
        'csvw>=1.5.6"',
        'clldutils>=2.8.0',
        'pycldf>=1.7.0',
    ],
    extras_require={
        "borrowing": ["matplotlib", "scipy"],
        "cluster": ["python-igraph", "scikit-learn"],
        "test": ["pytest", "coverage", "pytest-mock", "pytest-cov"],
    },
    entry_points={"console_scripts": ["lingpy=lingpy.cli:main"]},
    keywords=[
        "historical linguistics",
        "sequence alignment",
        "computational linguistics",
        "dialectology",
        "cognate detection",
    ],
    classifiers=[
        "Natural Language :: English",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Operating System :: OS Independent",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Programming Language :: Python :: 3.5",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
        "Topic :: Scientific/Engineering",
        "Topic :: Text Processing :: Linguistic",
    ],
    url="http://lingpy.org",
    license="gpl-3.0",
    platforms=["unix", "linux", "windows"],
    include_package_data=True,
    exclude_package_data={},
    package_data={
        "": [
            "data/ipa/sampa.csv",
            "data/swadesh/swadesh.qlc",
            "data/orthography_profiles/*.prf",
            "tests/test_data/*.csv",
            "tests/test_data/*.qlc",
            "tests/test_data/*.msq",
            "tests/test_data/*.msa",
            "tests/test_data/*.tsv",
            "tests/test_data/*.nex",
            "tests/test_data/*.psa",
            "tests/test_data/*.psq",
            "tests/test_data/cldf/*.csv",
            "tests/test_data/cldf/*.json",
            "data/conceptlists/*.tsv",
            "data/conf/*.rc",
            "data/models/*/converter",
            "data/models/*/INFO",
            "data/models/*/matrix",
            "data/models/*/scorer",
            "data/models/dvt/diacritics",
            "data/models/dvt/vowels",
            "data/models/dvt/tones",
            "data/models/dvt_el/diacritics",
            "data/models/dvt_el/vowels",
            "data/models/dvt_el/tones",
            "data/templates/*.html",
            "data/templates/*.js",
            "data/templates/*.css",
            "data/templates/*.tex",
            "data/templates/*.nex",
            "data/swadesh/swadesh.qlc",
        ]
    },
)
